export * from './main-page';
export * from './about-page';
export * from './not-found-page';
export * from './profile-page';
export * from './article-page';
export * from './article-details-page';
export * from './article-edit-page';
export * from './article-create-page';
export * from './admin-panel-page';
