name: linting, testing, building
on:
  push:
    branches: [ main, feature ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install fix
        run: npm i --force
      - name: install modules
        run: npm run build:prod
      - name: run lint ts
        run: npm run lint:ts
      - name: run lint scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run test:unit
